# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_prowadzacy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_prowadzacy(object):
    def setupUi(self, Dialog_prowadzacy):
        Dialog_prowadzacy.setObjectName("Dialog_prowadzacy")
        Dialog_prowadzacy.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog_prowadzacy)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_zdjecie = QtWidgets.QLabel(Dialog_prowadzacy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_zdjecie.sizePolicy().hasHeightForWidth())
        self.label_zdjecie.setSizePolicy(sizePolicy)
        self.label_zdjecie.setMaximumSize(QtCore.QSize(200, 200))
        self.label_zdjecie.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_zdjecie.setStyleSheet("")
        self.label_zdjecie.setText("")
        self.label_zdjecie.setPixmap(QtGui.QPixmap(":/icons/photo-man.jpg"))
        self.label_zdjecie.setScaledContents(True)
        self.label_zdjecie.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zdjecie.setObjectName("label_zdjecie")
        self.horizontalLayout.addWidget(self.label_zdjecie)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_imie = QtWidgets.QLabel(Dialog_prowadzacy)
        self.label_imie.setObjectName("label_imie")
        self.verticalLayout.addWidget(self.label_imie)
        self.label_opis = QtWidgets.QLabel(Dialog_prowadzacy)
        self.label_opis.setObjectName("label_opis")
        self.verticalLayout.addWidget(self.label_opis)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog_prowadzacy)
        QtCore.QMetaObject.connectSlotsByName(Dialog_prowadzacy)

    def retranslateUi(self, Dialog_prowadzacy):
        _translate = QtCore.QCoreApplication.translate
        Dialog_prowadzacy.setWindowTitle(_translate("Dialog_prowadzacy", "Dialog"))
        self.label_imie.setText(_translate("Dialog_prowadzacy", "TextLabel"))
        self.label_opis.setText(_translate("Dialog_prowadzacy", "TextLabel"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_prowadzacy = QtWidgets.QDialog()
    ui = Ui_Dialog_prowadzacy()
    ui.setupUi(Dialog_prowadzacy)
    Dialog_prowadzacy.show()
    sys.exit(app.exec_())
